# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('ege', models.SmallIntegerField(default=0)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('code', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
