# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priem', '0002_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('education_form_type', models.CharField(default='normal', max_length=50)),
                ('plan_all', models.IntegerField(default=0)),
                ('plan_contract', models.IntegerField(default=0)),
                ('plan_paid', models.IntegerField(default=0)),
                ('applications_all', models.IntegerField(default=0)),
                ('applications_contract', models.IntegerField(default=0)),
                ('applications_paid', models.IntegerField(default=0)),
                ('hors_concours', models.IntegerField(default=0)),
                ('medal', models.IntegerField(default=0)),
                ('olympiad', models.IntegerField(default=0)),
                ('original', models.IntegerField(default=0)),
                ('contest_all', models.IntegerField(default=0)),
                ('contest_contract', models.IntegerField(default=0)),
                ('contest_paid', models.IntegerField(default=0)),
                ('short_name', models.CharField(max_length=100)),
                ('original_all', models.PositiveIntegerField(default=0)),
                ('original_contract', models.PositiveIntegerField(default=0)),
                ('original_paid', models.PositiveIntegerField(default=0)),
                ('group_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('education_level_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('export_to_fis', models.PositiveSmallIntegerField(default=1)),
                ('fis_id', models.CharField(max_length=45)),
                ('original_first_wave', models.IntegerField(default=0)),
                ('plan_hors_concours', models.IntegerField(default=0)),
                ('original_hors_concours', models.IntegerField(default=0)),
                ('fis_suffix', models.CharField(max_length=45)),
                ('contest_hors_concours', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priem.Department')),
            ],
        ),
    ]
