# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priem', '0004_exam_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('exam_form', models.CharField(max_length=15)),
                ('result_form', models.CharField(max_length=4)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priem.Discipline')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priem.Speciality')),
            ],
        ),
    ]
