# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priem', '0005_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfactory_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('mark', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
